bank_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'bank_app'

urlpatterns = [
    path('', views.index, name="index"),
    path('add_user', views.add_user, name="add_user"),
    path('change_rank', views.change_rank, name="change_rank"),
    path('add_account', views.add_account, name="add_account"),
    path('transfer_money', views.transfer_money, name="transfer_money"),
    path('make_loan', views.make_loan, name="make_loan"),
    path('<int:Costumer_id>/', views.account_detail, name="account_detail"),

 ]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bank/', include('bank_app.urls')),
    path('accounts/', include('login_app.urls')),
]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
   path('login/', views.login, name='login'),
   path('logout/', views.logout, name='logout'),
  # path('password_reset/', views.password_reset, name='password_reset'),
   path('sign_up/', views.sign_up, name='sign_up'),
  # path('delete_account/', views.delete_account, name='delete_account'),
]

bank_app/models.py
from django.contrib.auth.models import User
from django.db import models, transaction
from django.db.models import Sum
from django.db.models.functions import Abs
from uuid import uuid4
from decimal import Decimal


# Create your models here.

class Costumer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15)
    rank = models.CharField(max_length=15, default="Basic")
    is_employee = models.BooleanField(default=False)

    @property
    def can_make_loans(self):
        if self.rank == "Gold" or self.rank == "Silver":
            return True
        else:
            return False

    def __str__(self):
        return f"{self.user} - {self.rank} - {self.can_make_loans}"


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    is_account = models.BooleanField(default=True)

    
    @property
    def balance(self):
        # return Ledger.objects.filter(account=self).aggregate(Sum('amount') or Decimal(0)
        return Ledger.objects.filter(account=self).aggregate(Sum('amount'))['amount__sum'] or Decimal(0)


    def __str__(self):
        return f"{self.user} - {self.name}"



class Ledger(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    text = models.CharField(max_length=75)
    timestamp = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=100)

    @classmethod
    def transaction(cls, amount, text, debit_account, credit_account):
        transaction_id = uuid4()
        amount_negative = -int(amount)

        debit_account = Account.objects.get(id=debit_account)
        credit_account = Account.objects.get(id=credit_account)


        with transaction.atomic():

            credit = Ledger()
            credit.account = credit_account
            credit.amount = amount_negative
            credit.text = text
            credit.transaction_id = transaction_id
            credit.save()

            debit = Ledger()
            debit.account = debit_account
            debit.amount = int(amount)
            debit.text = text
            debit.transaction_id = transaction_id
            debit.save()

    
    def __str__(self):
        return f"{self.account} - {self.amount} - {self.transaction_id}"

bank_app/forms.py
from django import forms
from .models import Costumer, User

class CostumerForm(forms.ModelForm):
    class Meta:
        model = Costumer
        exclude = ()

class AddCostumer(forms.Form):
    phone = forms.CharField()
    rank = forms.CharField()
    is_employee = forms.BooleanField(required=False)

bank_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Costumer, Account, Ledger
from .forms import CostumerForm, AddCostumer

# Create your views here

@login_required
def index(request):

    costumer_form = AddCostumer()
    users = User.objects.all()
    all_accounts = Account.objects.all()
    accounts = Account.objects.filter(user=request.user, is_account=True)
    loans = Account.objects.filter(user=request.user, is_account=False)

    # get costumer of logged in user, pass it to template
    costumer = Costumer.objects.get(user=request.user)

    context = {
        'accounts': accounts,
        'loans': loans,
        'all_accounts': all_accounts,
        'users': users,
        'costumer': costumer,
        'costumer_form': costumer_form,
    }

    return render(request, 'bank_app/index.html', context)


def add_user(request):
    #try:

        if request.method == "POST":
            username = request.POST['username']
            firstname = request.POST['firstname']
            lastname = request.POST['lastname']
            password = request.POST['password']
            email = request.POST['email']
            phone = request.POST['phone']
            rank = request.POST['rank']

            # doesnt work
            def is_employee(request):
                if request.POST.get('is_employee'):
                    return True
                else:
                    return False
            
            user = User.objects.create_user(username, email, password)

            if user:

                user.first_name = firstname
                user.last_name = lastname
                user.save()

                costumer = Costumer()

                costumer.user = user
                costumer.phone = phone
                costumer.is_employee = is_employee(request)
                costumer.save()

        return HttpResponseRedirect(reverse('bank_app:index'))
    
    #except:
        #return HttpResponse('<h1>Username has already been used - try again</h1>')


def change_rank(request):

    pk = request.POST['pk']
    rank = request.POST['rank']
    user = User.objects.get(pk=pk)
    costumer = Costumer.objects.get(user=user)
    costumer.rank = rank
    costumer.save()

    return HttpResponseRedirect(reverse('bank_app:index'))


def add_account(request):
    pk = request.POST['pk']
    account_name = request.POST['account']
    user = User.objects.get(pk=pk)
    account = Account(user=user, name=account_name)
    account.save()

    return HttpResponseRedirect(reverse('bank_app:index'))


def transfer_money(request):

    credit_id = request.POST['from_account']
    debit_id = request.POST['to_account']
    amount = request.POST['amount']
    text = request.POST['text']

# check if debit_id exists

    if Account.objects.filter(id=debit_id).exists():

        if Account.objects.get(user=request.user, id=credit_id).balance >= int(amount):

            Ledger.transaction(amount, text, debit_id, credit_id)
            return HttpResponseRedirect(reverse('bank_app:index'))

        else:
            return HttpResponse("<h1>Sorry, insufficient funds</h1>")

    else:
        return HttpResponse("<h1>Sorry, receiver account doesn't exist</h1>")



def make_loan(request):

    amount = request.POST['amount']
    text = request.POST['text']
    loan_name = request.POST['loan_name']

    # get id of debit account
    account_id = request.POST['account_name']

    account = Account(user=request.user, name=loan_name, is_account=False)
    account.save()
    
    # get id of credit account
    loan_id = account.id

    # if the given account name exists and belongs to the user

    if Account.objects.filter(user=request.user, id=account_id).exists():
        Ledger.transaction(amount, text, account_id, loan_id)

    return HttpResponseRedirect(reverse('bank_app:index'))



def account_detail(request, Costumer_id): 

    try:
        user = User.objects.get(id=Costumer_id)
    except User.DoesNotExist:
        raise Http404("User does not exist")


    costumer = Costumer.objects.get(user=request.user)
    accounts = Account.objects.filter(user=user)

    # ledgers must be account instance

    ledgers = Ledger.objects.filter(account__in=accounts).order_by('-timestamp')

    

    context = {
        'user' : user,
        'accounts' : accounts, 
        'ledgers' : ledgers
    }

    if costumer.is_employee or Costumer_id == request.user.id:
        return render(request, 'bank_app/account_detail.html', context)
    else:
        raise Http404("not employee")


    
    

bank_app/templates/bank_app/account_detail.html
{% extends 'bank_app/base.html' %}

{% block content %}

<a href="{% url 'bank_app:index' %}"></a>

<h1>user: {{ user }}</h1>

<br>

<h1>Accounts:</h1>

<div>
	{% for account in accounts %}

	<p> Account id: {{ account.id }} - {{ account.name }} - {{ account.balance }} $ </p>

	{% endfor %}

</div>

<h2> Transactions: 📒</h2>

{% for ledger in ledgers %}

<div style="font-style: italic; margin: 10px 0">

	{{ ledger.account }} -
	{{ ledger.amount }} -
	{{ ledger.text }} -
	{{ ledger.timestamp }} -
	{{ ledger.transaction_id }} -

</div>

{% endfor %}



{% endblock %}

bank_app/templates/bank_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   {% load static %}
   <link rel="stylesheet" type="text/css" href="{% static "main/css/main.css" %}">
   <title>Bank</title>
</head>
<body>
   <h1>Cold Friday bank 🤑</h1>
   <p>Welcome {{ user }} 🎉 - <a href="{% url 'login_app:logout' %}">Log out</a></p>
      {% block content %}
      {% endblock %}
      {% block footer %}
      {% endblock %}
</body>
</html>

bank_app/templates/bank_app/index.html
{% extends "bank_app/base.html" %}

{% block content %}

{% if costumer.is_employee %}

<p>Your rank: {{ costumer.rank }}</p>

	<h3>Employee Zone ✍️</h3>	

	<h2>Add user</h2>
	<form action="{% url 'bank_app:add_user' %}" method="POST">
		{% csrf_token %}
             	<input type="text" name="username" placeholder="username">
		<input type="text" name="firstname" placeholder="firstname">
		<input type="text" name="lastname" placeholder="lastname">
		<input type="text" name="password" placeholder="password">
		<input type="text" name="email" placeholder="email">
		{{ costumer_form }}
		<button>Add User</button>
	</form>


	<h2>All users</h2>

	<p>Add account: Insert account name</p>

	{% for user in users %}

	<h4>{{ user.username }}</h4>

	<a href="{{ user.id }}">Account details</a>
	
	<form action="{% url 'bank_app:change_rank' %}" method="POST">
		{% csrf_token %}
		<div style="display: flex">
			<input type="radio" id="gold" name="rank" value="Gold">
			<label for="gold">Gold</label>
			<input type="radio" id="silver" name="rank" value="Silver">
			<label for="silver">Silver</label>
			<input type="radio" id="basic" name="rank" value="Basic">
			<label for="basic">Basic</label>
			<button>Update</button>
		</div>
		<input type="hidden" name="pk" value="{{ user.pk }}">
	</form>

	<form action="{% url 'bank_app:add_account' %}" method="POST">
		{% csrf_token %}
		<input type="text" name="account" placeholder="account name">
		<input type="hidden" name="pk" value="{{ user.pk }}">
		<button>Add new</button>
	</form>

	<div style="margin:15px 0;"></div>

	{% endfor %}


{% endif %}

<h3>User Zone 👨</h3> 

<a href="{{ user.id }}" >My account details</a>


<h2>My Loans </h2>

{% for loan in loans %}

<p>Loan id: {{loan.id}} - {{ loan.name }} // {{ loan.balance }} $</p>

{% endfor %}


<h2>My Accounts</h2>

{% for account in accounts %}

<p> Account id: {{account.id}} - {{ account.name }} // {{ account.balance }} $</p>

{% endfor %}
	

{% if costumer.can_make_loans %}

	<h2>Make a loan 📝</h2>

	<form action="{% url 'bank_app:make_loan' %}" method="POST">
		{% csrf_token %}
		<input type="text" name="loan_name" placeholder="loan name">
		
		<label>My accounts:</label>
		<select name="account_name" placeholder="My accounts">
		{% for account in accounts %}
		<option value="{{ account.id }}">{{ account.name }}</option>
		{% endfor %}
		</select>


		<input type="text" name="text" placeholder="loan comment">
		<input type="number" name="amount" placeholder="amount">
		<button>Make loan</button>
	</form>

{% endif %}

<h2>Transfer Money 💸💰</h2>

<form action="{% url 'bank_app:transfer_money' %}" method="POST">
	{% csrf_token %}
	<label>My accounts:</label>
	<select name="from_account" placeholder="My accounts">
	{% for account in accounts %}
	<option value="{{ account.id }}">{{ account.name }}</option>
	{% endfor %}
	</select>

	<input type="text" name="to_account" placeholder="receiver account id" >
	<input type="text" name="text" placeholder="transaction comment">
	<input type="number" name="amount" placeholder="amount">
	<button>Send</button>
</form>

{% endblock %}